# Generated by Django 4.2.6 on 2023-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_password_lenghtpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='lenghtPassword',
        ),
        migrations.AddField(
            model_name='password',
            name='lengthPassword',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='password',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
