# Generated by Django 4.2.1 on 2023-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_password_lenghtpassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="password",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
