# Generated by Django 4.2.1 on 2023-11-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_user_alter_password_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
