# Generated by Django 4.2.6 on 2023-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_password_lenghtpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='id',
        ),
        migrations.AlterField(
            model_name='password',
            name='lengthPassword',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='password',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
